export const CARD_ADD_ITEM = 'CARD_ADD_ITEM';
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
